### ISSUE TITLE
How to Save image backend PHP

### ISSUE THREAD

**Issue by tojobbws** [editor-js/image#88] opened 2020-06-15 10:01 UTC
I have followed the example but cannot work.

```
const editor = new EditorJS({
		autofocus: true,
		tools: {
			embed: Embed,
			image: {
				class: ImageTool,
				config: {
					endpoints: {
						byFile: 'http://localhost/editor/uploadfile.php' // Your backend file uploader endpoint
						
					}
				}
			}
		}
    });
```

In uploadfile.php

`<?php
print_r($_FILE);
?>`

**Comment by kaaaaaaaaaaai** [comment] 2020-06-15 10:21
is typo? `$_FILES`

**Comment by tojobbws** [comment] 2020-06-15 10:45
Thank you
I forgot S
$_FILE > $_FILES
> is typo? `$_FILES`

**Comment by kaaaaaaaaaaai** [comment] 2020-06-15 10:54
np.
im glad the problem is solve. ^-^b

could you close this issue if there are not any problems.

**Comment by leonsegal** [comment] 2020-07-14 19:19
How would you access the file in node.js? When I log req.body it is just an empty object e.g. `{}`.

**Closed** 2020-07-19 07:54 UTC
